---
services:
  postgres:
    image: postgres:16
    container_name: relen_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: MyVeryStrongPassword
      POSTGRES_DB: relen
    ports: [5432:5432]
    volumes:
      - postgres:/var/lib/postgresql
volumes:
  postgres:
